### ISSUE TITLE
AML storage in 03 doesn't seem to get the right storage account info

### ISSUE THREAD

**Issue by maxkazmsft** [Azure/Batch-Scoring-Deep-Learning-Models-With-AML#24]
# datastore

my_datastore = Datastore.register_azure_blob_container(

    workspace=ws, 

    datastore_name=my_datastore_name, 

    container_name=get_key(env_path, "STORAGE_CONTAINER_NAME"), 

    account_name=get_key(env_path, "STORAGE_ACCOUNT_NAME"), 

    account_key=get_key(env_path, "STORAGE_ACCOUNT_KEY"),

    overwrite=True

)

---------------------------------------------------------------------------
HttpOperationError                        Traceback (most recent call last)
~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/data/datastore_client.py in _register(ws, dto, create_if_not_exists, overwrite, auth, host)
    311             client.data_store.create(ws._subscription_id, ws._resource_group, ws._workspace_name,
--> 312                                      dto, create_if_not_exists)
    313         except HttpOperationError as e:

~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/_restclient/operations/data_store_operations.py in create(self, subscription_id, resource_group_name, workspace_name, dto, create_if_not_exists, custom_headers, raw, **operation_config)
    162         if response.status_code not in [200]:
--> 163             raise HttpOperationError(self._deserialize, response)
    164 

HttpOperationError: Operation returned an invalid status code 'Azure Storage Error. Please make sure the credential is correct.'

During handling of the above exception, another exception occurred:

HttpOperationError                        Traceback (most recent call last)
<ipython-input-28-16822e6c5d3f> in <module>()
      6     account_name=get_key(env_path, "STORAGE_ACCOUNT_NAME"),
      7     account_key=get_key(env_path, "STORAGE_ACCOUNT_KEY"),
----> 8     overwrite=True
      9 )

~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/core/datastore.py in register_azure_blob_container(workspace, datastore_name, container_name, account_name, sas_token, account_key, protocol, endpoint, overwrite, create_if_not_exists)
    113         return Datastore._client().register_azure_blob_container(workspace, datastore_name, container_name,
    114                                                                  account_name, sas_token, account_key, protocol,
--> 115                                                                  endpoint, overwrite, create_if_not_exists)
    116 
    117     @staticmethod

~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/data/datastore_client.py in register_azure_blob_container(workspace, datastore_name, container_name, account_name, sas_token, account_key, protocol, endpoint, overwrite, create_if_not_exists)
     86         return _DatastoreClient._register_azure_storage(
     87             workspace, datastore_name, constants.AZURE_BLOB, container_name, account_name, credential_type,
---> 88             sas_token or account_key, protocol, endpoint, overwrite, create_if_not_exists)
     89 
     90     @staticmethod

~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/data/datastore_client.py in _register_azure_storage(ws, datastore_name, storage_type, container_name, account_name, credential_type, credential, protocol, endpoint, overwrite, create_if_not_exists, auth, host)
    276         datastore = DataStoreDto(datastore_name, storage_type, storage_dto)
    277         module_logger.debug("Converted data into DTO")
--> 278         return _DatastoreClient._register(ws, datastore, create_if_not_exists, overwrite, auth, host)
    279 
    280     @staticmethod

~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/data/datastore_client.py in _register(ws, dto, create_if_not_exists, overwrite, auth, host)
    316                 client = _DatastoreClient._get_client(ws, auth, host)
    317                 client.data_store.update(dto.name, ws._subscription_id, ws._resource_group,
--> 318                                          ws._workspace_name, dto, create_if_not_exists)
    319             else:
    320                 module_logger.error("Registering datastore failed with {} error code and error message\n{}"

~/anaconda3/envs/batchscoringdl_aml/lib/python3.6/site-packages/azureml/_restclient/operations/data_store_operations.py in update(self, name, subscription_id, resource_group_name, workspace_name, dto, create_if_not_exists, custom_headers, raw, **operation_config)
    338 
    339         if response.status_code not in [200]:
--> 340             raise HttpOperationError(self._deserialize, response)
    341 
    342         if raw:

HttpOperationError: Operation returned an invalid status code 'Data store being updated does not exist.'

**Comment by jiata** [comment]
stale
