### ISSUE TITLE
failing AML pipeline in notebook 03

### ISSUE THREAD

**Issue by maxkazmsft** [Azure/Batch-Scoring-Deep-Learning-Models-With-AML#25]
in pipelin_run command get:

Experiment | Id | Type | Status | Details Page | Docs Page
-- | -- | -- | -- | -- | --
style_transfer_mpi | 35cbbd6e-2173-4433-9337-010287a76d70 | azureml.PipelineRun | Failed | Link to Azure Portal | Link to Documentation

**Comment by jiata** [comment]
@maxkazmsft following up

**Comment by jiata** [comment]
closing since stale
